<?php
// Plugin definition
$plugin = array(
  'title' => t('Amberroad Click Through Page'),
  'icon' => 'ra-rke-ctp.png',
  'category' => t('Amberroad'),
  'theme' => 'ra_rke_ctp',
  'regions' => array(
    'header' => t('Header'),
    'row1-content' => t('Main Content'),
    'row1-flex' => t('Row 1 (flex)'),
    'row1-full' => t('Row 1 full'),
   
    'row2-full' => t('Row 2 full'),
  
    'row3-full' => t('Row 3 full'),
    'row3-2col1' => t('Row 3 (left)'),
    'row3-2col2' => t('Row 3 (right)'),

    'row4-full' => t('Row 4 full'),

    'row5-full' => t('Row 5 full'),
    'row5-2col1' => t('Row 5 (left)'),
    'row5-2col2' => t('Row 5 (right)'),
  ),
);

