<?php
// Plugin definition
$plugin = array(
  'title' => t('AmberRoad Internal 1'),
  'icon' => 'ar-internal-1.png',
  'category' => t('Amberroad'),
  'theme' => 'ar_internal_1',
  'regions' => array(
    'header' => t('Header'),
    'row1-content' => t('Main Content'),
    'row1-sidebar' => t('Content sidebar'),
    'row2' => t('Row 2 full'),
    'row2-2col1' => t('Row 2 (left)'),
    'row2-2col2' => t('Row 2 (right)'),
    'row3-main' => t('Row 3 - main'),
    'row3-right1' => t('Row 3 - right1'),
    'row3-right2' => t('Row 3 - right2'),
    'row3-short-main' => t('Row 3 (2) - main'),
    'row3-short-right1' => t('Row 3 (2) - right1'),
    'row3-short-right2' => t('Row 3 (2) - right2'),
    'row4-full' => t('Row 4 full'),
    'row4-left' => t('Row 4 - left'),
    'row4-content' => t('Row 4 - main'),
    'row5-2col1' => t('Row 5 (left)'),
    'row5-2col2' => t('Row 5 (right)'),
  ),
);
