<?php
/**
 * @file
 * amberroad_fpp.features.uuid_fpp.inc
 */

/**
 * Implements hook_uuid_features_default_fpps().
 */
function amberroad_fpp_uuid_features_default_fpps() {
  $fpps = array();

  $fpps[] = array(
    'timestamp' => 1461333199,
    'title' => '',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Donaldson Company: Customer Testimonial',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454252753,
    'uuid' => '04327ccc-e9c2-46fa-a233-5db40ed736ff',
    'language' => '',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p><span style="color:#FF8C00;"><span style="font-size: 20px;">Donaldson Company: Customer Testimoial</span></span></p>

<p><span style="font-size:16px;">Discover why Donaldson selected Amber Roads solutions as best in class by watching the video today!<span style="color: rgb(22, 138, 204);"> Discover why Donaldson selected Amber Roads selected Amber</span></span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(
      'und' => array(
        0 => array(
          'value' => 'aEjt4sbjpoEYsd59f1KAhw',
          'format' => NULL,
        ),
      ),
    ),
    'field_video_width' => array(
      'und' => array(
        0 => array(
          'value' => 460,
        ),
      ),
    ),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  $fpps[] = array(
    'timestamp' => 1454189446,
    'title' => '',
    'log' => '',
    'bundle' => 'image',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454189376,
    'uuid' => '0a8c5576-956b-4a3e-b5bb-c642eb4c20b6',
    'language' => 'und',
    'field_basic_image_caption' => array(),
    'field_basic_image_image' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '49c6ee44-3c4b-4fe4-b8da-8976ef7b5cd2',
  );
  $fpps[] = array(
    'timestamp' => 1473682179,
    'title' => 'Collaborate',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1457684425,
    'uuid' => '0f191ede-2962-4063-903a-cea406c72972',
    'language' => '',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p class="rtecenter"><span style="font-size:16px;">Improve supplier performance and accelerate time-to-market with consistent and timely information.</span></p>

<p class="rtecenter"><span style="font-size:18px;"><a href="html/search/resources?field_solution_area_tid%5B%5D =57&amp;field_solution_area_tid%5B%5D =60&amp;field_solution_area_tid%5B%5D =18" target="_blank">Learn More »</a></span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  $fpps[] = array(
    'timestamp' => 1462456517,
    'title' => 'Agilent (logo + testimonial)',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454276404,
    'uuid' => '14092e7c-c5f4-45b5-b7ec-f923be3718a5',
    'language' => '',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p><em><span style="font-size:16px;">“We needed a truly global integrated import/export trade compliance solution to support our high volume transactions. Now our worldwide solution interfaces with multiple ERP systems and 1,300 users in 42 countries.”</span></em></p>

<p class="rteright"><span style="font-size:16px;"><strong>Vice President Logistics<br />
Agilent Technologies</strong></span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => 'e60c210d-3121-44ba-bd0b-be34ff079b59',
  );
  $fpps[] = array(
    'timestamp' => 1462456902,
    'title' => 'NCR (logo + testimonial)',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Testimonial NCR',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454276550,
    'uuid' => '142f0ac5-bef7-4e92-8b2f-8921d93e1cd9',
    'language' => 'und',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p><span style="font-size:16px;"><em>“Once you can see the shipments moving in transit, you can see when something’s going to be late and adjust to it. That’s helped to reduce the amount of expediting that we’ve had to do. NCR will see a seven-figure benefit from the implementation; it has added definite value for us.”</em></span></p>

<p class="rteright"><span style="font-size:16px;"><strong>Director, Global Logistics Sourcing<br />
NCR</strong></span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => 'e60c210d-3121-44ba-bd0b-be34ff079b59',
  );
  $fpps[] = array(
    'timestamp' => 1454189844,
    'title' => '',
    'log' => '',
    'bundle' => 'image',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454189844,
    'uuid' => '226aa9f5-75ea-42e9-a4d1-15746dc09aa0',
    'language' => 'und',
    'field_basic_image_caption' => array(),
    'field_basic_image_image' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '49c6ee44-3c4b-4fe4-b8da-8976ef7b5cd2',
  );
  $fpps[] = array(
    'timestamp' => 1454196137,
    'title' => '',
    'log' => '',
    'bundle' => 'video',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454196137,
    'uuid' => '259ebd0c-acbe-4442-b510-38a330e56843',
    'language' => '',
    'field_video_file' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '49c6ee44-3c4b-4fe4-b8da-8976ef7b5cd2',
  );
  $fpps[] = array(
    'timestamp' => 1458132359,
    'title' => '',
    'log' => '',
    'bundle' => 'text',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1458132348,
    'uuid' => '25dcd8c4-32bc-478e-ad3c-310e3499f461',
    'language' => 'und',
    'field_basic_text_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p>This is some text</p>
',
          'format' => 'full_html',
        ),
      ),
    ),
    'rdf_mapping' => array(),
    'user_uuid' => '49c6ee44-3c4b-4fe4-b8da-8976ef7b5cd2',
  );
  $fpps[] = array(
    'timestamp' => 1462021953,
    'title' => '',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Video SDV',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1457711077,
    'uuid' => '2c98a478-a55b-414a-a421-6c7af9fe274f',
    'language' => 'und',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p><span style="color:#FF8C00;"><span style="font-size: 20px;">Customer Testimonial: Ocean Procurement Manager, SDV</span></span></p>

<p><span style="font-size:16px;">In this video Heidi Lindemann, Ocean Procurement Manager for SDV points out the key benefits that they have realized such as more expedient response times to customers with competitive quotes, better visibility into contracts across 40,000 rates, and improved visibility into transportation costs on a global scale.</span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(
      'und' => array(
        0 => array(
          'value' => 'hkmXUZOxoUA-R8mCRZn_ZA',
          'format' => NULL,
        ),
      ),
    ),
    'field_video_width' => array(
      'und' => array(
        0 => array(
          'value' => 460,
        ),
      ),
    ),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  $fpps[] = array(
    'timestamp' => 1460053838,
    'title' => 'Solution brochure',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Solution brochure',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1457703866,
    'uuid' => '39573e77-9907-44da-abd2-670f24f3eb22',
    'language' => '',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p class="rtecenter"><span style="font-size:20px;">ANALYST REPORT<br />
<img alt="" src="/sites/default/files/line.png" style="width: 221px; height: 17px;" /></span><br />
<img alt="" height="42" src="/sites/default/files/scd_logo.png" width="175" /></p>

<p class="rtecenter"><span style="font-size:16px;"><span style="font-size: 20px;">2016 Global<br />
Sourcing &amp; Trade<br />
Management</span></span></p>

<p class="rtecenter"><span style="font-size:16px;"><a href="http://info.amberroad.com/rl_AnalystReport_SupplyChainDigest-GlobalSourcingGTMBenchmarkStudyDec.2015_LandingPage.html" target="_blank">Download Now »</a></span></p>

<p class="rtecenter">&nbsp;</p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  $fpps[] = array(
    'timestamp' => 1462370343,
    'title' => '',
    'log' => '',
    'bundle' => 'text',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454511290,
    'uuid' => '3ba893b9-07b7-45f2-b4f1-efa4945e764b',
    'language' => 'und',
    'field_basic_text_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p>&nbsp;</p>

<p>&nbsp;</p>

<h1><span style="font-size:26px;">THE WORLD LEADER IN CLOUD-BASED GLOBAL TRADE MANAGEMENT SOFTWARE</span></h1>
',
          'format' => 'full_html',
        ),
      ),
    ),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  $fpps[] = array(
    'timestamp' => 1462282749,
    'title' => 'Find out more',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Find out more',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1457705360,
    'uuid' => '63de82a7-2bfd-4585-aee3-0d4ee79c3423',
    'language' => '',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p class="rtecenter">&nbsp;</p>

<p class="rtecenter"><span style="font-size:20px;">TO FIND OUT MORE<br />
<img alt="" src="/sites/default/files/line.png" style="width: 221px; height: 17px;" /></span><br />
<img alt="" height="70" src="/sites/default/files/icon_rl.png" width="77" /><br />
<span style="font-size:16px;"><span style="font-size: 20px;">Please visit our<br />
Resource Library</span></span></p>

<p class="rtecenter"><span style="font-size:16px;"><a href="http://www.amberroad.com/html/search/resources" target="_blank">Visit Now »</a></span></p>

<p class="rtecenter">&nbsp;</p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => 'e60c210d-3121-44ba-bd0b-be34ff079b59',
  );
  $fpps[] = array(
    'timestamp' => 1462464030,
    'title' => 'Comply',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1457690564,
    'uuid' => '6670766f-2722-452d-b2b8-00a1ca4cd4b4',
    'language' => 'und',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p class="rtecenter"><span style="font-size:16px;">Automate import/export regulations  to enable goods to flow unimpeded  across international borders while  reducing duties.</span></p>

<p class="rtecenter"><span style="font-size:18px;"><a href="html/search/resources?field_solution_area_tid%5B%5D =53&amp;field_solution_area_tid%5B%5D =52&amp;field_solution_area_tid%5B%5D =45&amp;field_solution_area_tid%5B%5D =22&amp;field_solution_area_tid%5B%5D =56&amp;field_solution_area_tid%5B%5D =55&amp;field_solution_area_tid%5B%5D =65&amp;field_solution_area_tid%5B%5D =15" target="_blank">Learn More »</a></span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  $fpps[] = array(
    'timestamp' => 1477503786,
    'title' => 'Featured',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454203934,
    'uuid' => '68eba7be-87d4-4fbe-9b74-c484dfa328a1',
    'language' => 'und',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p class="rtecenter"><span style="font-size:24px;"><span style="color: rgb(255, 140, 0);">eBook</span></span><br />
<span style="font-size:22px;"><span class="lpContentsItem richTextSpan">ACE: How to Meet the 2016 Single Window Mandate Now</span></span></p>

<p class="rtecenter"><span style="font-size:18px;"><span style="font-size:20px;"><img alt="Download our Analyst Report: The New GTM: Connecting Upstream Decisions to Improve Downstream Execution" height="85" src="/sites/default/files/ace-ebook.jpg" width="203" /></span></span></p>

<p class="rtecenter"><span style="font-size:18px;"><a href="http://info.amberroad.com/rl-eBook-AceSingleWindow_Landingpage.html" target="_blank">Download Now »</a></span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  $fpps[] = array(
    'timestamp' => 1478790464,
    'title' => 'Upcoming Events',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454204073,
    'uuid' => '6a1a28a4-4a29-4f36-8ac8-1d0f2b87d000',
    'language' => 'und',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p class="rtecenter"><span style="font-size:20px;">BIS Complying with Export Controls Austin</span></p>

<p class="rtecenter">&nbsp;</p>

<p class="rtecenter"><span style="font-size:22px;"><img alt="Learn more about the BIS Complying with Export Controls Austin" src="/sites/default/files/bis2012.png" style="width: 254px; height: 62px; margin-top: 10px; margin-bottom: 10px;" /></span></p>

<p class="rtecenter"><span style="font-size:14px;">Austin, TX | December 7-8, 2016</span></p>

<p class="rtecenter"><a href="http://bit.ly/2edRnNt" target="_blank"><span style="font-size:18px;">Learn More »</span></a></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => 'e60c210d-3121-44ba-bd0b-be34ff079b59',
  );
  $fpps[] = array(
    'timestamp' => 1457689740,
    'title' => 'Connect',
    'log' => '',
    'bundle' => 'video_and_text',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1457689740,
    'uuid' => '825fdf61-9674-49d6-82bb-1b0bfb4b696c',
    'language' => 'und',
    'rdf_mapping' => array(),
    'user_uuid' => '49c6ee44-3c4b-4fe4-b8da-8976ef7b5cd2',
  );
  $fpps[] = array(
    'timestamp' => 1463473431,
    'title' => '',
    'log' => '',
    'bundle' => 'text',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454327124,
    'uuid' => '86284f3c-a125-4e38-ae4a-81414ab82f7e',
    'language' => '',
    'field_basic_text_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p class="front-page-logos" style="text-align:center"><span style="font-size:30px;font-weight:100;color:gb(251, 137, 9);">The world\'s largest and fastest-growing companies use Amber Road</span></p>

<p>&nbsp;</p>

<div class="container-fluid front-page-logos">
<div class="row">
<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Agilent Technologies" src="/sites/default/files/Client_logo/hp-agilent_0.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Amway" src="/sites/default/files/Client_logo/hp-amway_0.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="AXALTA" src="/sites/default/files/Client_logo/hp-axalta_0.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Baker Hughes" src="/sites/default/files/Client_logo/hp-bakerhughes.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Bloomin Brands" src="/sites/default/files/hp-bloomin-brands.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Bunzl" src="/sites/default/files/Client_logo/hp-bunzl_0.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Caleres" src="/sites/default/files/Client_logo/hp-caleres.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="CISCO" src="/sites/default/files/Client_logo/hp-cisco.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Construction Specialties" src="/sites/default/files/Client_logo/hp-constructionspecialists.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Donaldson Filtration Solutions" src="/sites/default/files/Client_logo/hp-donaldson.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Electrocomponents plc" src="/sites/default/files/Client_logo/hp-electrocomponents.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Fairchild" src="/sites/default/files/Client_logo/hp-fairfield.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="FUJIFILM" src="/sites/default/files/Client_logo/hp-fujifilm.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="General Electric" src="/sites/default/files/Client_logo/hp-ge.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="General Mills" src="/sites/default/files/Client_logo/hp-generalmills.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="GlaskoSmithKline" src="/sites/default/files/Client_logo/hp-gsk.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Haworth" src="/sites/default/files/Client_logo/hp-hayworth.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Honeywell" src="/sites/default/files/Client_logo/hp-honeywell.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Ingersoll Rand" src="/sites/default/files/Client_logo/hp-ingersollrand.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Intelsat" src="/sites/default/files/Client_logo/hp-intelsat.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Kraft" src="/sites/default/files/Client_logo/hp-kraft.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Leggett &amp; Platt" src="/sites/default/files/Client_logo/hp-leggettplatt.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Levi\'s" src="/sites/default/files/Client_logo/hp-levis.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Mercury Marine" src="/sites/default/files/Client_logo/hp-mercury.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Monsanto" src="/sites/default/files/hp-monsanto.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="NCR" src="/sites/default/files/Client_logo/hp-ncr.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="OpenText" src="/sites/default/files/Client_logo/hp-opentext.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Pfizer" src="/sites/default/files/Client_logo/hp-pfizer.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Qualcomm" src="/sites/default/files/Client_logo/hp-qualcomm.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Siemens" src="/sites/default/files/Client_logo/hp-siemens.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Steelcase" src="/sites/default/files/Client_logo/hp-steelcase.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Tyco" src="/sites/default/files/Client_logo/hp-tyco.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Unilever" src="/sites/default/files/Client_logo/hp-unilever.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="UPS" src="/sites/default/files/Client_logo/hp-ups.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="VF" src="/sites/default/files/Client_logo/hp-vf.png" style="width: 150px; height: 103px;" /></div>

<div class="col-lg-1 col-md-3 col-sm-6 col-xs-12"><img alt="Weatherford" src="/sites/default/files/Client_logo/hp-weatherford.png" style="width: 150px; height: 103px;" /></div>
</div>
</div>
',
          'format' => 'full_html',
        ),
      ),
    ),
    'rdf_mapping' => array(),
    'user_uuid' => 'f8e4dc80-0460-487c-9f97-8ebc06dc5d96',
  );
  $fpps[] = array(
    'timestamp' => 1454604788,
    'title' => 'Recent Blog Posts',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454604734,
    'uuid' => '8c76ec35-5e30-45e4-89ce-98717f08cfe3',
    'language' => '',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<script language="JavaScript" src="http://feed2js.org/feed2js.php?src=http://blog.amberroad.com/blog/topic/supply-chain-visibility/rss.xml+&amp;num=4&amp;targ=y&amp;utf=y" charset="UTF-8" type="text/javascript"></script>',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '49c6ee44-3c4b-4fe4-b8da-8976ef7b5cd2',
  );
  $fpps[] = array(
    'timestamp' => 1458933229,
    'title' => 'Webinar image',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Webinar image',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1457704891,
    'uuid' => 'afbc9ec4-6c3e-430f-875a-4537e256c444',
    'language' => 'und',
    'field_basic_image_image' => array(),
    'field_button' => array(
      'und' => array(
        0 => array(
          'url' => 'http://www.amberroad.com',
          'title' => 'Webinar image',
          'attributes' => array(
            'target' => 0,
          ),
        ),
      ),
    ),
    'field_text' => array(),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  $fpps[] = array(
    'timestamp' => 1462456557,
    'title' => 'Fairchild (logo + testimonial)',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454276682,
    'uuid' => 'b5b2168d-1675-41d2-9fdb-ad2681c14f8c',
    'language' => '',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p><em><span style="font-size:16px;">“We’ve simplified our shipment process, automated documentation and trade party screening, and gained regulatory and financial control over our international shipments. Currently 90% of all of Fairchild’s shipments are pre-cleared.”</span></em></p>

<p class="rteright"><span style="font-size:16px;"><strong>Senior Manager, Global Logistics<br />
Fairchild Semiconductor</strong></span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => 'e60c210d-3121-44ba-bd0b-be34ff079b59',
  );
  $fpps[] = array(
    'timestamp' => 1473358032,
    'title' => '',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Tyco Security: Customer Testimonial',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454252636,
    'uuid' => 'b686baaf-f02c-4d70-b3fc-7ed3ceaa099f',
    'language' => '',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p><span style="color:#FF8C00;"><span style="font-size: 20px;">Tyco Security: Customer Testimonial</span></span></p>

<p><span style="font-size:16px;">Vice President of International Trade Compliance at Tyco Security discusses how Amber Road\'s global trade management solutions enable its supply chain to stay optimized.</span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(
      'und' => array(
        0 => array(
          'value' => 'hjlSXS33yX_BS7Zb0lI6Rw',
          'format' => NULL,
        ),
      ),
    ),
    'field_video_width' => array(
      'und' => array(
        0 => array(
          'value' => 460,
        ),
      ),
    ),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  $fpps[] = array(
    'timestamp' => 1462463647,
    'title' => 'Connect',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1457690288,
    'uuid' => 'c438ed68-3176-43e5-bff7-efdc60bb1289',
    'language' => 'und',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p class="rtecenter"><span style="font-size:16px;">Enable every participant in your global supply chain to access critical information, automate cross-border transactions, and gain control.</span></p>

<p class="rtecenter"><span style="font-size:18px;"><a href="html/search/resources?field_solution_area_tid%5B%5D =59&field_solution_area_tid%5B%5D =32&field_solution_area_tid%5B%5D =39" target="_blank">Learn More »</a></span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  $fpps[] = array(
    'timestamp' => 1478790335,
    'title' => 'New Webinar',
    'log' => '',
    'bundle' => 'box',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454203995,
    'uuid' => 'c9f26cd5-977f-4e90-aea4-f16287a00d37',
    'language' => 'und',
    'field_basic_image_image' => array(),
    'field_button' => array(),
    'field_text' => array(
      'und' => array(
        0 => array(
          'value' => '<p class="rtecenter"><span style="font-size:22px;"><span class="lpContentsItem richTextSpan"><span style="font-family: arial,helvetica,sans-serif;">Quality is Stitched into the<br />
Supply Chain: A Vera Bradley Case Study</span></span></span></p>

<p class="rtecenter"><img alt="" src="/sites/default/files/gta_webinar2_2.jpg" style="width: 285px; height: 75px;" /></p>

<p class="rtecenter"><span style="font-size: 14px;">November 17, 2016 | 2PM EST</span></p>

<p class="rtecenter"><span style="font-size:18px;"><a href="http://bit.ly/2eMPsn3">Register Now »</a></span></p>
',
          'summary' => '',
          'format' => 'full_html',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_video' => array(),
    'field_video_width' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => 'e60c210d-3121-44ba-bd0b-be34ff079b59',
  );
  $fpps[] = array(
    'timestamp' => 1454532884,
    'title' => 'What our customers say about Amber Road',
    'log' => '',
    'bundle' => 'text',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454338124,
    'uuid' => 'ccc59eaa-6426-4615-8385-2ace32a00fc1',
    'language' => 'und',
    'field_basic_text_text' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '49c6ee44-3c4b-4fe4-b8da-8976ef7b5cd2',
  );
  $fpps[] = array(
    'timestamp' => 1457703316,
    'title' => '',
    'log' => '',
    'bundle' => 'image',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Solution Brochure',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1457703316,
    'uuid' => 'd18e5a4c-b91a-4f8a-920c-179a8b033e05',
    'language' => '',
    'field_basic_image_caption' => array(),
    'field_basic_image_image' => array(),
    'rdf_mapping' => array(),
    'user_uuid' => '49c6ee44-3c4b-4fe4-b8da-8976ef7b5cd2',
  );
  $fpps[] = array(
    'timestamp' => 1461918750,
    'title' => 'Recent Blog Posts',
    'log' => '',
    'bundle' => 'text',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => '',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1454604841,
    'uuid' => 'fefeb0a2-db21-42fa-84bd-9699a4e094b5',
    'language' => 'und',
    'field_basic_text_text' => array(
      'und' => array(
        0 => array(
          'value' => '<script language="JavaScript" src="http://blog.amberroad.com/blog/topic/export-management/rss.xml&num=5&targ=y&ut" type="text/javascript"></script>',
          'format' => 'full_html',
        ),
      ),
    ),
    'rdf_mapping' => array(),
    'user_uuid' => '6a9160bf-66af-4f32-8762-15863747f066',
  );
  return $fpps;
}
