<?php
/**
 * @file
 * amberroad_resources.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function amberroad_resources_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Large Enterprise Business',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '004486b7-3329-4bf1-9b77-91e436edb9dd',
    'vocabulary_machine_name' => 'audience',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'BOFU',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '10771a1f-130c-4771-af6f-f5f3b92fe693',
    'vocabulary_machine_name' => 'buying_stage',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Transportation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '26678942-4dab-43d6-b799-bc114ae7efd1',
    'vocabulary_machine_name' => 'persona',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Apparel',
    'description' => '',
    'format' => 'full_html',
    'weight' => 1,
    'uuid' => '2682dec0-aa8b-4b72-91be-63f7277d2726',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Import Management',
    'description' => '',
    'format' => 'full_html',
    'weight' => 10,
    'uuid' => '2f5d12b7-be90-40f4-9c62-1e5266f2cfc1',
    'vocabulary_machine_name' => 'solution_area',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Supply Chain',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3d570404-764d-47d6-9d09-40dfd0e5cb4a',
    'vocabulary_machine_name' => 'persona',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sourcing Optimization',
    'description' => '',
    'format' => 'full_html',
    'weight' => 13,
    'uuid' => '3d804663-2b0b-47da-8156-9c4708b9ee38',
    'vocabulary_machine_name' => 'solution_area',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Supplier Management',
    'description' => '',
    'format' => 'full_html',
    'weight' => 14,
    'uuid' => '49b00c95-0855-439b-b337-541cf38d19ba',
    'vocabulary_machine_name' => 'solution_area',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Infographics',
    'description' => '',
    'format' => 'full_html',
    'weight' => 5,
    'uuid' => '645623e0-3584-4511-8850-3fa081f26318',
    'vocabulary_machine_name' => 'resource_type',
    'field_resource_search_logo' => array(),
    'field_external_link' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Videos',
    'description' => '',
    'format' => 'full_html',
    'weight' => 12,
    'uuid' => '6759852c-1988-4f75-a754-d1047b6d8922',
    'vocabulary_machine_name' => 'resource_type',
    'field_resource_search_logo' => array(),
    'field_external_link' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Chemical',
    'description' => '',
    'format' => 'full_html',
    'weight' => 3,
    'uuid' => '6dbd5d8d-fe98-46a5-88d6-f1c3cba0b937',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Export Management',
    'description' => '',
    'format' => 'full_html',
    'weight' => 4,
    'uuid' => '6f367cee-02f5-4ed4-8bdb-19df6b84c8de',
    'vocabulary_machine_name' => 'solution_area',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Financial Services',
    'description' => '',
    'format' => 'full_html',
    'weight' => 5,
    'uuid' => '8158c2bc-78c1-405b-a5c2-fdb4ab4ced70',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Higher Education',
    'description' => '',
    'format' => 'full_html',
    'weight' => 6,
    'uuid' => '819d1aef-2044-4269-974d-f5dc9c10fcfe',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Compliance',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8346eaf4-8962-4b91-b569-b555180c9200',
    'vocabulary_machine_name' => 'persona',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Industry Resources',
    'description' => '',
    'format' => 'full_html',
    'weight' => 4,
    'uuid' => '84e944bf-2750-429a-b8a0-ad669231010b',
    'vocabulary_machine_name' => 'resource_type',
    'field_resource_search_logo' => array(),
    'field_external_link' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Automotive',
    'description' => '',
    'format' => 'full_html',
    'weight' => 2,
    'uuid' => '8644723a-bb21-4095-a3ea-b70a71539d58',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Upcoming Webinars',
    'description' => '',
    'format' => 'full_html',
    'weight' => 11,
    'uuid' => '8aaea498-df7b-42b0-b540-51a43b08f153',
    'vocabulary_machine_name' => 'resource_type',
    'field_resource_search_logo' => array(),
    'field_external_link' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'On-Demand Webinars',
    'description' => '',
    'format' => 'full_html',
    'weight' => 6,
    'uuid' => '8caaa895-f626-46a4-8cc0-2f1ebdce721e',
    'vocabulary_machine_name' => 'resource_type',
    'field_resource_search_logo' => array(),
    'field_external_link' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Life Sciences',
    'description' => '',
    'format' => 'full_html',
    'weight' => 8,
    'uuid' => '91768fb1-1e52-44d6-8007-0292842f23d6',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'IT',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '932a984e-5414-4cf2-aa02-0d9a249a3e76',
    'vocabulary_machine_name' => 'persona',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Supply Chain Visibility',
    'description' => '',
    'format' => 'full_html',
    'weight' => 15,
    'uuid' => '94393afb-8ab0-4feb-b632-5b43a6300031',
    'vocabulary_machine_name' => 'solution_area',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'High Technology',
    'description' => '',
    'format' => 'full_html',
    'weight' => 7,
    'uuid' => 'a34f7437-8b95-4a97-9437-e0c158aea5fe',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Oil & Gas',
    'description' => '',
    'format' => 'full_html',
    'weight' => 11,
    'uuid' => 'a821d297-f275-474a-9dcf-313d403471ab',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Consumer Goods',
    'description' => '',
    'format' => 'full_html',
    'weight' => 4,
    'uuid' => 'ad8bb721-7af8-4142-89ed-6df522b6dd60',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Finance',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b00c1b39-65bb-4194-9e5f-55f85872f8f5',
    'vocabulary_machine_name' => 'persona',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'MOFU',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b2e2204e-4f0e-40a5-a170-3ff8807c612b',
    'vocabulary_machine_name' => 'buying_stage',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Procurement',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b6794c5c-dc0c-42aa-adf7-f52f7ad88d95',
    'vocabulary_machine_name' => 'persona',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Transportation Management',
    'description' => '',
    'format' => 'full_html',
    'weight' => 17,
    'uuid' => 'ba7a7a90-a24b-4f66-9618-4971cc1776e8',
    'vocabulary_machine_name' => 'solution_area',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'TOFU',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'be16958d-499e-4edf-9d82-78a0e8029878',
    'vocabulary_machine_name' => 'buying_stage',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Logistics Providers',
    'description' => '',
    'format' => 'full_html',
    'weight' => 9,
    'uuid' => 'ceb58d39-9823-44d5-a06b-b088a9ed9e1e',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Aerospace & Defense',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd1a45250-cae8-4bc9-a439-f150deb223ec',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Podcasts',
    'description' => '',
    'format' => 'full_html',
    'weight' => 7,
    'uuid' => 'd66f53a9-f5bb-4e93-bd7a-dbe02f27d0a9',
    'vocabulary_machine_name' => 'resource_type',
    'field_resource_search_logo' => array(),
    'field_external_link' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Retail',
    'description' => '',
    'format' => 'full_html',
    'weight' => 12,
    'uuid' => 'd7007795-15ec-4e4e-94df-834a232b3342',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Duty Management',
    'description' => '',
    'format' => 'full_html',
    'weight' => 3,
    'uuid' => 'f22a4cc8-965c-4123-8dc9-021f7cc941fc',
    'vocabulary_machine_name' => 'solution_area',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Small - Medium Size Business',
    'description' => '',
    'format' => 'full_html',
    'weight' => 1,
    'uuid' => 'f94a4734-ae8f-4a5f-a01e-82c38df5c001',
    'vocabulary_machine_name' => 'audience',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Manufacturing',
    'description' => '',
    'format' => 'full_html',
    'weight' => 10,
    'uuid' => 'fcf05bf5-4ded-4774-a8b9-97562bf52cad',
    'vocabulary_machine_name' => 'industry',
    'metatags' => array(),
  );
  return $terms;
}
