<?php
/**
 * @file
 * amberroad_panels.fieldable_panels_pane_type.inc
 */

/**
 * Implements hook_default_fieldable_panels_pane_type().
 */
function amberroad_panels_default_fieldable_panels_pane_type() {
  $export = array();

  $fieldable_panels_pane_type = new stdClass();
  $fieldable_panels_pane_type->disabled = FALSE; /* Edit this to true to make a default fieldable_panels_pane_type disabled initially */
  $fieldable_panels_pane_type->api_version = 1;
  $fieldable_panels_pane_type->name = 'box';
  $fieldable_panels_pane_type->title = 'Box';
  $fieldable_panels_pane_type->description = '';
  $export['box'] = $fieldable_panels_pane_type;

  return $export;
}
